export const PLAYER_ACTION_TYPES = {
    'SET_PLAYER_TO_PAUSE' : 'player/SET_PLAYER_TO_PAUSE',
    'SET_PLAYER_TO_PLAY' : 'player/SET_PLAYER_TO_PLAY',
    'SET_PLAYER_TO_LOOP' : 'player/SET_PLAYER_TO_LOOP',
    'SET_PLAYER_TO_LAST_POSITION' : 'player/SET_PLAYER_TO_LAST_POSITION',
    'SET_PLAYER_ERROR' : 'player/SET_PLAYER_ERROR',
}