export const SONGS_ACTION_TYPES = {
    'SET_SONG' : 'song/SET_SONG',
    'FETCH_TRACK_DETAIL_START' : 'song/FETCH_TRACK_DETAIL_START',
    'FETCH_TRACK_DETAIL_SUCCESS' : 'song/FETCH_TRACK_DETAIL_SUCCESS',
    'FETCH_TRACK_DETAIL_FAILED' : 'song/FETCH_TRACK_DETAIL_FAILED',
}

