export const SONGS_ACTION_TYPES = {
    'SET_SONG' : 'song/SET_SONG',
    'FETCH_TRACK_DETAIL_START' : 'song/FETCH_TRACK_DETAIL_START',
    'FETCH_TRACK_DETAIL_SUCCESS' : 'song/FETCH_TRACK_DETAIL_SUCCESS',
    'FETCH_TRACK_DETAIL_FAILED' : 'song/FETCH_TRACK_DETAIL_FAILED',
    'SET_CURRENT_QUEUE' : 'song/SET_CURRENT_QUEUE',
    'SET_QUEUE_LISTS' : 'song/SET_QUEUE_LISTS',
    'CACHED_SONG' : 'song/CACHED_SONG',
}

