export const SONGS_ACTION_TYPES = {
    'SET_SONG' : 'song/SET_SONG',
    'FETCH_TRACK_DETAIL_START' : 'song/FETCH_TRACK_DETAIL_START',
    'FETCH_TRACK_DETAIL_SUCCESS' : 'song/FETCH_TRACK_DETAIL_SUCCESS',
    'FETCH_TRACK_DETAIL_FAILED' : 'song/FETCH_TRACK_DETAIL_FAILED',
    'SET_FETCH_SONG_RETRY' : 'song/SET_FETCH_SONG_RETRY',
    'SET_CURRENT_QUEUE' : 'song/SET_CURRENT_QUEUE',
    'SET_QUEUE_LISTS' : 'song/SET_QUEUE_LISTS',
    'SET_SONG_DEFAULT_IMAGE' : 'song/SET_SONG_DEFAULT_IMAGE',
    'GET_NEW_TRACK_QUEUE' : 'song/GET_NEW_TRACK_QUEUE',
    'CACHED_SONG' : 'song/CACHED_SONG',
}

