export const TRACK_ACTION_TYPES = {
    'FETCH_TRACK_START' : 'track/FETCH_TRACK_START',
    'FETCH_TRACK_FAILED': 'track/FETCH_TRACK_FAILED',
    'FETCH_TRACK_SUCCESS' : 'track/FETCH_TRACK_SUCCESS',
    'CACHE_TRACK' : 'track/CACHE_TRACK'
}