export const ALBUM_ACTION_TYPES = {
    'FETCH_ALBUM_START' : 'album/FETCH_ALBUM_START',
    'FETCH_ALBUM_SUCCESS' : 'album/FETCH_ALBUM_SUCCESS',
    'FETCH_ALBUM_FAILED' : 'album/FETCH_ALBUM_FAILED',
    'CACHE_ALBUM' : 'album/CACHE_ALBUM',
}