export const ARTISTS_PROFILE_ACTION_TYPES =  {
    FETCH_ARTISTS_PROFILE_START : 'artists/profile/FETCH_ARTISTS_PROFILE_START',
    FETCH_ARTISTS_PROFILE_SUCCESS : 'artists/profile/FETCH_ARTISTS_PROFILE_SUCCESS',
    FETCH_ARTISTS_PROFILE_FAILED : 'artists/profile/FETCH_ARTISTS_PROFILE_FAILED',
}