export const SEARCH_ACTION_TYPES = {
    'FETCH_SEARCH_START' : 'search/FETCH_SEARCH_START',
    'FETCH_SEARCH_FAILED' : 'search/FETCH_SEARCH_FAILED',
    'FETCH_SEARCH_SUCCESS' : 'search/FETCH_SEARCH_SUCCESS',
    'RESET_SEARCH' : 'search/RESET_SEARCH',
    'CACHE_SEARCH' : 'search/CACHE_SEARCH',
}