export const GENRE_ACTION_TYPES = {
    'FETCH_GENRE_START' : 'genre/FETCH_GENRE_START',
    'FETCH_GENRE_FAILED' : 'genre/FETCH_GENRE_FAILED',
    'FETCH_GENRE_SUCCESS' : 'genre/FETCH_GENRE_SUCCESS',
    'CACHE_GENRE' : 'genre/CACHE_GENRE'
}