export const ARTISTS_ACTION_TYPES =  {
    FETCH_ARTISTS_START : 'artists/FETCH_ARTISTS_START',
    FETCH_ARTISTS_SUCCESS : 'artists/FETCH_ARTISTS_SUCCESS',
    FETCH_ARTISTS_FAILED : 'artists/FETCH_ARTISTS_FAILED',
}