export const PLAYLIST_ACTION_TYPES = {
    'FETCH_PLAYLIST_START' : 'playlist/FETCH_PLAYLIST_START',
    'FETCH_PLAYLIST_SUCCESS' : 'playlist/FETCH_PLAYLIST_SUCCESS',
    'FETCH_PLAYLIST_FAILED' : 'playlist/FETCH_PLAYLIST_FAILED',
    'CACHE_PLAYLIST' : 'playlist/CACHE_PLAYLIST',
}