export const HOME_ACTION_TYPES = {
    'FETCH_HOME_METADATA_START' : 'home/FETCH_HOME_METADATA_START',
    'FETCH_HOME_METADATA_FAILED' : 'home/FETCH_HOME_METADATA_FAILED',
    'FETCH_HOME_METADATA_SUCCESS' : 'home/FETCH_HOME_METADATA_SUCCESS',
}